// Auto-generated by Project Sentinel
// Authentication fixtures for multi-role testing

export const testRoles = {
  default: {
,
  },
};

export async function loginAs(page: any, role: string) {
  const credentials = testRoles[role as keyof typeof testRoles];
  if (!credentials) throw new Error(`Unknown role: ${role}`);
  await page.goto('https://openrouter.ai//login');
  await page.fill('#email', credentials.username || credentials.email || '');
  await page.fill('#password', credentials.password || '');
  await page.click('[type="submit"]');
  await page.waitForURL(/dashboard|home/);
}

export async function getAuthToken(page: any, role: string): Promise<string> {
  await loginAs(page, role);
  const storage = await page.context().storageState();
  const cookie = storage.cookies.find((c: any) => c.name.includes('token') || c.name.includes('session'));
  return cookie?.value || '';
}
