import { test, expect } from '@playwright/test';

// Auto-generated by Project Sentinel
// Workflow: Recorded Session
// Target: https://openrouter.ai

test.describe('Recorded Session - Happy Path', () => {
  test.step('GET https://shop.example.com/ → 200 OK', async () => {
    await page.goto('https://openrouter.ai');
    await expect(page).toHaveTitle(/.+/);
  });

  test.step('POST https://shop.example.com/api/login → 200 OK', async () => {
    await page.goto('https://openrouter.ai/login');
    await page.fill('#email', 'user@test.com');
    await page.fill('#password', 'correct-password');
    await page.click('[type="submit"]');
    await expect(page).toHaveURL(/dashboard/);
  });

  test.step('GET https://shop.example.com/api/users/1234567890 → 200 OK', async () => {
    const res = await page.request.get('https://openrouter.ai/api/users/1234567890');
    expect(res.status()).toBeLessThan(400);
  });

  test.step('GET https://shop.example.com/api/users/9999 → 200 OK', async () => {
    const res = await page.request.get('https://openrouter.ai/api/users/9999');
    expect(res.status()).toBeLessThan(400);
  });

  test.step('GET https://shop.example.com/api/admin/users → 200 OK', async () => {
    await page.goto('https://openrouter.ai/admin');
    await expect(page).toHaveURL(/admin/);
  });

  test.step('GET https://shop.example.com/api/products?search=laptop → 200 OK', async () => {
    await page.goto('https://openrouter.ai/products');
    await expect(page.locator('.product-list')).toBeVisible();
  });

  test.step('POST https://shop.example.com/api/checkout → 200 OK', async () => {
    await page.goto('https://openrouter.ai/checkout');
    await page.fill('#card-number', '4111111111111111');
    await page.fill('#expiry', '12/30');
    await page.fill('#cvv', '123');
    await page.click('[type="submit"]');
    await expect(page).toHaveURL(/order-confirmation/);
  });
});
