import fs from 'fs';
import path from 'path';
import type { ScenarioManifest } from './scenario-parser';

export class PlaywrightTestGenerator {
  private target: string;
  constructor(target: string) { this.target = target; }

  generateFromManifest(manifest: ScenarioManifest, outputDir: string): string[] {
    fs.mkdirSync(outputDir, { recursive: true });
    const generatedFiles: string[] = [];

    for (const workflow of manifest.workflows) {
      const safeName = workflow.name.toLowerCase().replace(/[^a-z0-9]/g, '-');

      const happyTest = this.generateHappyTest(workflow);
      const happyPath = path.join(outputDir, `${safeName}.spec.ts`);
      fs.writeFileSync(happyPath, happyTest);
      generatedFiles.push(happyPath);

      if (workflow.test.sad.length > 0) {
        const securityTest = this.generateSecurityTest(workflow);
        const securityPath = path.join(outputDir, `${safeName}-security.spec.ts`);
        fs.writeFileSync(securityPath, securityTest);
        generatedFiles.push(securityPath);
      }
    }

    const authFixture = this.generateAuthFixture(manifest);
    const fixturePath = path.join(outputDir, 'fixtures', 'auth.ts');
    fs.mkdirSync(path.dirname(fixturePath), { recursive: true });
    fs.writeFileSync(fixturePath, authFixture);
    generatedFiles.push(fixturePath);

    return generatedFiles;
  }

  private generateHappyTest(workflow: ScenarioManifest['workflows'][number]): string {
    const steps = workflow.test.happy.map((step) => `  test.step('${step}', async () => {\n${this.parseStep(step)}\n  });`).join('\n\n');
    return `import { test, expect } from '@playwright/test';\n\n// Auto-generated by Project Sentinel\n// Workflow: ${workflow.name}\n// Target: ${this.target}\n\ntest.describe('${workflow.name} - Happy Path', () => {\n${steps}\n});\n`;
  }

  private generateSecurityTest(workflow: ScenarioManifest['workflows'][number]): string {
    const sadTests = workflow.test.sad.map((step) => `  test('${step}', async ({ page }) => {\n${this.generateSecurityTestCode(step)}\n  });`).join('\n\n');
    return `import { test, expect } from '@playwright/test';\n\n// Auto-generated by Project Sentinel\n// Workflow: ${workflow.name}\n// Security tests for sad paths and vulnerability scenarios\n\ntest.describe('${workflow.name} - Security Tests', () => {\n${sadTests}\n});\n`;
  }

  private parseStep(step: string): string {
    const lower = step.toLowerCase();
    if (lower.includes('login') || lower.includes('valid credential')) return `    await page.goto('${this.target}/login');\n    await page.fill('#email', 'user@test.com');\n    await page.fill('#password', 'correct-password');\n    await page.click('[type="submit"]');\n    await expect(page).toHaveURL(/dashboard/);`;
    if (lower.includes('browse') || lower.includes('product')) return `    await page.goto('${this.target}/products');\n    await expect(page.locator('.product-list')).toBeVisible();`;
    if (lower.includes('checkout') || lower.includes('payment')) return `    await page.goto('${this.target}/checkout');\n    await page.fill('#card-number', '4111111111111111');\n    await page.fill('#expiry', '12/30');\n    await page.fill('#cvv', '123');\n    await page.click('[type="submit"]');\n    await expect(page).toHaveURL(/order-confirmation/);`;
    if (lower.includes('admin')) return `    await page.goto('${this.target}/admin');\n    await expect(page).toHaveURL(/admin/);`;
    return `    await page.goto('${this.target}');\n    // TODO: Implement step - "${step}"`;
  }

  private generateSecurityTestCode(step: string): string {
    const lower = step.toLowerCase();
    if (lower.includes('sql injection') || lower.includes('sqli')) return `    await page.goto('${this.target}/login');\n    await page.fill('#email', "' OR 1=1--");\n    await page.fill('#password', 'anything');\n    await page.click('[type="submit"]');\n    await expect(page).toHaveURL(/login/);\n    await expect(page.locator('.error')).toBeVisible();`;
    if (lower.includes('xss')) return `    await page.goto('${this.target}/search');\n    await page.fill('#q', '<script>alert("xss")</script>');\n    await page.click('[type="submit"]');\n    await expect(page.locator('script')).not.toBeVisible();\n    const content = await page.content();\n    expect(content).not.toContain('<script>');`;
    if (lower.includes('brute force') || lower.includes('rate limit')) return `    for (let i = 0; i < 10; i++) {\n      await page.goto('${this.target}/login');\n      await page.fill('#email', 'user@test.com');\n      await page.fill('#password', \`wrong-\${i}\`);\n      await page.click('[type="submit"]');\n    }\n    await expect(page.locator('.rate-limit, .too-many')).toBeVisible();`;
    if (lower.includes('idor') || lower.includes('other user')) return `    await page.goto('${this.target}/api/users/1');\n    const response = await page.request.get('${this.target}/api/users/2');\n    expect(response.status()).toBe(403);`;
    if (lower.includes('auth bypass') || lower.includes('admin') || lower.includes('403')) return `    await page.goto('${this.target}/admin');\n    await expect(page).toHaveURL(/login|unauthorized|forbidden/);`;
    if (lower.includes('tampered') || lower.includes('price')) return `    const response = await page.request.post('${this.target}/api/checkout', {\n      data: { items: [{ id: 1, price: 0.01 }] },\n    });\n    expect(response.status()).toBe(400);`;
    return `    // TODO: Implement security test - "${step}"\n    await page.goto('${this.target}');`;
  }

  private generateAuthFixture(manifest: ScenarioManifest): string {
    const roles = manifest.roles.map((role) => {
      const creds = Object.entries(role.credentials).map(([key, value]) => `      ${key}: '${value}'`).join(',\n');
      return `  ${role.name}: {\n${creds},\n  },`;
    }).join('\n');

    return `// Auto-generated by Project Sentinel\n// Authentication fixtures for multi-role testing\n\nexport const testRoles = {\n${roles}\n};\n\nexport async function loginAs(page: any, role: string) {\n  const credentials = testRoles[role as keyof typeof testRoles];\n  if (!credentials) throw new Error(\`Unknown role: \${role}\`);\n  await page.goto('${this.target}/login');\n  await page.fill('#email', credentials.username || credentials.email || '');\n  await page.fill('#password', credentials.password || '');\n  await page.click('[type="submit"]');\n  await page.waitForURL(/dashboard|home/);\n}\n\nexport async function getAuthToken(page: any, role: string): Promise<string> {\n  await loginAs(page, role);\n  const storage = await page.context().storageState();\n  const cookie = storage.cookies.find((c: any) => c.name.includes('token') || c.name.includes('session'));\n  return cookie?.value || '';\n}\n`;
  }
}
